source("analise.R")
names(df)
df %>% group_by(location, termo, lang) %>% count()
df %>% filter(lang == "en") %>% group_by(location, termo, lang) %>% count()
df %>% filter(lang == "es") %>% group_by(location, termo, lang) %>% count()
df %>% filter(lang == "es") %>% group_by(location, termo, lang) %>% count() %>% arrange(n) %>%  tail(30)
df %>% filter(lang == "es") %>% group_by(location, termo, lang) %>% count() %>% arrange(n) %>%  tail(20)
df %>% filter(lang == "es") %>% group_by(location, termo) %>% count() %>% arrange(n) %>%  tail(20)
df %>% filter(lang == "es") %>% group_by(termo) %>% count() %>% arrange(n) %>%  tail(20)
df %>% filter(lang == "en") %>% group_by(termo) %>% count() %>% arrange(n) %>%  tail(20)
df %>% group_by(termo, lang) %>% count() %>% arrange(n) %>%  tail(20)
df %>% filter(term == "STF")
df %>% filter(termo == "STF")
df %>% filter(termo == "STF") %>% select(message)
df %>% filter(termo == "STF") %>% select(text)
range(df$created_at)
df %>% filter(created_at > ymd("2019-11-07"))
df %>% filter(created_at >= ymd("2019-11-07"))
df <- df %>% filter(created_at >= ymd("2019-11-07"))
nrow(df)
df
df %>% filter(termo == "STF") %>% select(text)
df %>% filter(lang == "es") %>% filter(termo == "STF") %>% select(text)
df %>% filter(lang == "es") %>% filter(termo == "STF") %>% arrange(retweets_count)
names(df)
df %>% filter(lang == "es") %>% filter(termo == "STF") %>% arrange(retweet_count)
df %>% filter(lang == "es") %>% filter(termo == "STF") %>% arrange(retweet_count) %>% select(text)
df %>% filter(lang == "es") %>% filter(termo == "STF") %>% arrange(retweet_count) %>% select(screen_name)
df %>% filter(lang == "es") %>% filter(termo == "STF") %>% arrange(retweet_count) %>% select(screen_name, location)
df %>% filter(lang == "es") %>% filter(termo == "STF") %>% arrange(retweet_count) %>% select(screen_name, location, retweet_count)
df %>% filter(lang == "es") %>% group_by(screen_name, termo, location) %>% summarise(retweet_count = sum(retweet_count)) %>% arrange(retweet_count)
df %>% filter(lang == "es") %>% group_by(screen_name, termo, location) %>% summarise(retweet_count = sum(retweet_count)) %>% arrange(retweet_count) %>% tail(20)
df %>% filter(lang == "en") %>% group_by(screen_name, termo, location) %>% summarise(retweet_count = sum(retweet_count)) %>% arrange(retweet_count) %>% tail(20)
savehistory("log.R")
